In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
# conda install numpy

In [4]:
import numpy as np

In [5]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
#numpy is a library helps to print list in 2d and 3d so that we can use to plot graph and analyse the data

In [9]:
y = np.array(x)

In [10]:
y # 2d list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
x1 = [[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]

In [12]:
y1 = np.array(x1)

In [13]:
y1 # 3d array

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [14]:
# methods in numpy

In [15]:
x = [1,2,3,4,5]

In [16]:
y = [[1,2,3],[4,5,6],[7,8,9]]

In [17]:
np.array(x)

array([1, 2, 3, 4, 5])

In [18]:
x

[1, 2, 3, 4, 5]

In [19]:
np.array(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# square matrix are when rows and column are same i = row , j = column => i==j --> square matrix

In [22]:
np.zeros(3) # 1d zero matrix

array([0., 0., 0.])

In [23]:
np.zeros((2,3)) #2d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.zeros(((2,3,4))) #3d 

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [29]:
np.zeros((2,3)) + 5 #2d 

array([[5., 5., 5.],
       [5., 5., 5.]])

In [30]:
# ones matrix

In [31]:
np.ones(2)

array([1., 1.])

In [32]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
# identity matrix

In [37]:
np.eye(4) # i == j 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
# range

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(50).reshape(5,10) #2d array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [44]:
# linspace

In [48]:
np.linspace(0,100,5) #linear space

array([  0.,  25.,  50.,  75., 100.])

In [49]:
# max

In [50]:
x = [1,2,3,4,5]

In [52]:
y = np.array(x) 

In [53]:
y.max()

5

In [54]:
y.min()

1

In [ ]:
# index

In [67]:
y.argmax() # max value index

4

In [68]:
y.argmin() # min value index

0

In [56]:
# random value

In [57]:
np.random.rand()

0.023012763734255093

In [58]:
np.random.rand(4)

array([0.53237678, 0.50282718, 0.27391519, 0.48169509])

In [66]:
np.random.randint(100)

2

In [70]:
# indexing and slicing

In [78]:
x = np.arange(0,20)

In [79]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [80]:
x[2]

2

In [81]:
x[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
x[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [85]:
x[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [86]:
x.argmax()

19

In [87]:
y = x[10:20] 

In [88]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [89]:
y = x[10:20] = 40  # working with y will affect x

In [90]:
y

40

In [91]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40])

In [93]:
y = x.copy() # working with y won't affect x

In [94]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40])

In [95]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40])

In [103]:
y[10:20] = np.arange(10,20)

In [104]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [105]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40])

In [106]:
# 2d array slicing and indexing

In [107]:
x = np.arange(25).reshape(5,5)

In [108]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# indexing

In [109]:
# x[i][j] --> i => row and j => column

In [110]:
x[1][2]

7

In [112]:
x[1,2]

7

In [122]:
# slicing

In [123]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [131]:
x[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [132]:
# conditional selection

In [133]:
y = np.arange(1,20)

In [134]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [135]:
y>12

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [137]:
y[y>12]

array([13, 14, 15, 16, 17, 18, 19])

In [139]:
y[y % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [140]:
# operations on numpy

In [141]:
x  = np.arange(10)

In [142]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
y  = np.arange(10,20)

In [144]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [147]:
z = x + y

In [148]:
z # index with x and y will be added

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [149]:
z = x / y

In [150]:
z

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [151]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [152]:
np.log(x)

C:\Users\Venomhere\AppData\Local\Temp\ipykernel_8164\1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [153]:
np.max(x)

9

In [155]:
x = np.arange(12).reshape(3,4)

In [156]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [157]:
y = np.arange(10,22).reshape(3,4)

In [158]:
y

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [159]:
z = x + y 

In [160]:
z

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [167]:
y = np.arange(12).reshape(3,4)

In [168]:
x = np.arange(12).reshape(4,3)

In [170]:
y


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [172]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [173]:
z = x + y # diff row and column index can't be added

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [174]:
# sum 

In [181]:
x = np.arange(1,11)

In [182]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [183]:
sum(x)

55

In [ ]:
# learn more about numpy by googling --> list of numpy operations